name: C/C++ Build (Ubuntu)

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    uses: owner/repo/.github/workflows/build.yml@main
